// GENERATED by api/mine-hero-assets.cjs — do not edit by hand.
//
// The nine coins the /mine hero fills its glass with, in the render's own
// pixel coordinates. These are the same ellipses the pile sprite's alpha was
// cut with, which is why this file is generated rather than kept in step by
// hand: the two drifting apart shows up as a crescent of empty glass around a
// coin, and nothing about that is visible in a diff.
//
// Order is the order they are revealed in — bottom row left to right, then the
// middle row, then the top two, because a heap builds from the bottom.

/** Where the sprite sits in the art, and how big it is. */
export const PILE_SPRITE = { x: 313, y: 335, w: 137, h: 80 } as const;

/** The cut-out radius of one coin. */
export const PILE_RX = 15.6;
export const PILE_RY = 13.1;

/** Coin centres, in reveal order. */
export const PILE_COINS: ReadonlyArray<{ x: number; y: number }> = [
  { x: 331, y: 398 },
  { x: 362.5, y: 398 },
  { x: 395.5, y: 398 },
  { x: 430.5, y: 397 },
  { x: 348, y: 378 },
  { x: 378.5, y: 377 },
  { x: 411.5, y: 384 },
  { x: 374, y: 351 },
  { x: 393.5, y: 358 },
];
